"""empty message

Revision ID: cc9faeb50f8e
Revises: e0fe5fc326e9
Create Date: 2021-12-06 23:58:35.118442

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cc9faeb50f8e'
down_revision = 'e0fe5fc326e9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Car', sa.Column('status1', sa.String(), nullable=True))
    op.create_unique_constraint(None, 'Car', ['id'])
    op.create_unique_constraint(None, 'Order', ['id'])
    op.create_unique_constraint(None, 'User', ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'User', type_='unique')
    op.drop_constraint(None, 'Order', type_='unique')
    op.drop_constraint(None, 'Car', type_='unique')
    op.drop_column('Car', 'status1')
    # ### end Alembic commands ###
